### ISSUE TITLE
ModuleNotFoundError: No module named 'PoolSet'

### ISSUE THREAD

**Issue by HappyDay-design** [LMozart/sumo-multiagent#2]
Hello. Thank for your code
When running your model, it had errors
ModuleNotFoundError: No module named 'PoolSet'

I tried to install but I can not run your model

**Comment by HappyDay-design** [comment]
Traceback (most recent call last):
  File "/home/osboxes/Desktop/sumo-multiagent/PoolFactory/PoolFactory.py", line 1, in <module>
    from PoolSet.MultiAgentPool import MultiAgentPool
  File "/home/osboxes/Desktop/sumo-multiagent/PoolFactory/PoolSet/MultiAgentPool.py", line 2, in <module>
    from PoolFactory.Pool import ExperiencePool
  File "/home/osboxes/Desktop/sumo-multiagent/PoolFactory/PoolFactory.py", line 1, in <module>
    from PoolSet.MultiAgentPool import MultiAgentPool
ImportError: cannot import name 'MultiAgentPool' from 'PoolSet.MultiAgentPool' (/home/osboxes/Desktop/sumo-multiagent/PoolFactory/PoolSet/MultiAgentPool.py)
